# infra/helm/backend/values.yaml
replicaCount: 3
image:
  repository: ghcr.io/your-repo/backend
  tag: latest
service:
  type: ClusterIP
  port: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
