# .github/workflows/backend.yml
name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: go test ./...
      - name: Build Docker Image
        run: docker build --repo ${{ github:repository }}
      - name: Push Docker Image
        run: |
         gh login ${{ github:repository }} \
          docker push ${{ github:repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

