# .github/workflows/backend.yml
name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: go test ./...
      - name: Build Docker Image
        run: docker build -t ghcr.io/your-repo/backend:latest .
      - name: Push Docker Image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin
          docker push ghcr.io/your-repo/backend:latest

