name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      
      # Run Go Tests
      - name: Run Go Tests
        run: go test ./...
      
      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t ghcr.io/Chrisadams777/ai-code-search-tool/docs:latest .
      
      # Push Docker Image to GitHub Container Registry
      - name: Push Docker Image
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${CR_PAT}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/Chrisadams777/ai-code-search-tool/docs:latest
