name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      # Install dependencies
      - name: Install Dependencies
        run: npm install
      
      # Build the project
      - name: Build Project
        run: npm run build
      
      # Copy build output to /docs for GitHub Pages
      - name: Move Build to Docs
        run: |
          rm -rf docs
          mv frontend/build docs
      
      # Commit and push /docs to GitHub
      - name: Commit and Push Docs
        run: |
          git config --global user.email "Chrisadams777@users.noreply.github.com"
          git config --global user.name "Chrisadams777"
          git add docs
          git commit -m "Deploy to GitHub Pages"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
