name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      # Install all dependencies, including devDependencies
      - name: Install Dependencies
        run: npm install
      
      # Build the project
      - name: Build Project
        run: npm run build
      
      # Set Git user identity for commits
      - name: Configure Git Identity
        run: |
          git config --global user.email "Chrisadams777@users.noreply.github.com"
          git config --global user.name "Chrisadams777"

      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
